/**
 * Generate npm package scaffold files for a jscodeshift codemod.
 * Returns file contents keyed by relative path.
 */

export interface ScaffoldFile {
  path: string;
  content: string;
  language: "javascript" | "json" | "markdown";
}

export function generateScaffold(transformCode: string): ScaffoldFile[] {
  const pkgJson = {
    name: "my-codemod",
    version: "0.1.0",
    description: "A jscodeshift codemod",
    main: "src/transform.js",
    scripts: {
      test: "jest",
    },
    keywords: ["codemod", "jscodeshift"],
    license: "MIT",
    dependencies: {
      jscodeshift: "^0.16.0",
    },
    devDependencies: {
      jest: "^29.0.0",
    },
  };

  const testCode = `const { describe, it, expect } = require("@jest/globals");
const { run: jscodeshift } = require("jscodeshift/src/testUtils");
const transform = require("../src/transform");

describe("transform", () => {
  it("transforms correctly", () => {
    const input = \`// paste your input here
const oldName = "hello";\`;

    const expected = \`// paste your expected output here
const newName = "hello";\`;

    const output = jscodeshift(transform, input, {});
    expect(output).toBe(expected);
  });
});
`;

  const readme = `# my-codemod

A [jscodeshift](https://github.com/facebook/jscodeshift) codemod.

## Usage

\`\`\`bash
npx jscodeshift --transform src/transform.js <path>
\`\`\`

## Options

| Option | Default | Description |
|--------|---------|-------------|
| \`--dry\` | false | Preview changes without writing |
| \`--print\` | false | Print changed files |
| \`--extensions\` | js | File extensions to transform |

## Development

\`\`\`bash
npm install
npm test
\`\`\`

## Generated by [codemod-studio](https://codemod-studio.vercel.app)
`;

  const gitignore = `node_modules/
*.log
`;

  return [
    {
      path: "src/transform.js",
      content: transformCode,
      language: "javascript",
    },
    {
      path: "package.json",
      content: JSON.stringify(pkgJson, null, 2),
      language: "json",
    },
    {
      path: "__tests__/transform.test.js",
      content: testCode,
      language: "javascript",
    },
    {
      path: "README.md",
      content: readme,
      language: "markdown",
    },
    {
      path: ".gitignore",
      content: gitignore,
      language: "markdown",
    },
  ];
}

/** Download a single file as a Blob in the browser */
export function downloadFile(filename: string, content: string, mimeType = "text/plain"): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
